# Generated by Django 2.0.4 on 2018-06-24 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Minid',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('BDBAG', 'BDBag')], max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
