# Generated by Django 2.1.4 on 2018-12-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAuthProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('client', models.UUIDField(help_text='Globus App credentials '
                                                      'used in the search')),
                ('group',
                 models.ForeignKey(help_text='The Group these searches should '
                                             'apply',
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='auth.Group')),
            ],
            options={
                'verbose_name_plural': 'SearchAuthProxies',
            },
        ),
    ]
